# Gebruik een Node.js image als basis
FROM node:22

# Stel de werkdirectory in
WORKDIR /app

# Kopieer en installeer dependencies
COPY package.json ./
RUN npm install
RUN npm install -g nodemon  # Nodemon installeren voor live reload

# Kopieer de rest van de code
COPY . .

# Start de applicatie met nodemon
CMD ["nodemon", "server.js"]
