version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  api:
    build:
      context: .
      dockerfile: Dockerfile  # Use Dockerfile.dev for development
    container_name: my-api-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: mongodb://admin:secretpassword@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
