name: CI - API

on:
  push:
    paths:
      - 'DevOpsWouterHendrix/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'DevOpsWouterHendrix/**'

jobs:
  test:
    name: Run tests for Node API
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DevOpsWouterHendrix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm install
        run: npm install

      - name: Run tests with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: DevOpsWouterHendrix
          test-script: npm test
