name: Run Week1 Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '22'  
              
          - name: Install dependencies
            run: |
              cd week1
              npm install

          - name: Start MongoDB
            run: sudo systemctl start mongod

          - name: Run tests
            run: |
              cd week1
              npm test
