name: Lint

on:
  push:
    paths:
      - 'DevOpsWouterHendrix/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'DevOpsWouterHendrix/**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DevOpsWouterHendrix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clean install (fix permissions)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run ESLint
        run: sudo npx eslint .